# docker-compose logs -f metabase

version: '3.6'

services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
    - metabase_data:/dev/random:ro
    ports:
      - 3080:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: secret
      MB_DB_HOST: postgres
    networks:
      - metanet1
    depends_on:
      - pg_metabase
  pg_metabase:
    image: postgres:12-alpine
    container_name: pg_metabase
    hostname: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: metabase
      POSTGRES_PASSWORD: secret
    volumes:
    - pg_metabase_data:/var/lib/postgresql/data
    networks:
      - metanet1

networks:
  metanet1:
    driver: bridge

volumes:
  metabase_data:
    driver: local
  pg_metabase_data:
    driver: local
