app = "domja-minio"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
image = "minio/minio:latest"

[experimental]
private_network = true
cmd = [ "server", "/data", "--console-address", ":9001" ]
allowed_public_ports = []
auto_rollback = true

[env]
  FLY_REGION = "sin"

[[mounts]]
  destination = "/data"
  source = "minio_data"

[[services]]
  internal_port = 9000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[services]]
    internal_port = 9001
    protocol = 'tcp'

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 9001

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
