version: '3.3'

services:
  traefik:
    container_name: traefik
    image: traefik:v2.7
    command:
      - --accesslog
      - --log.level=ERROR
      - --api.insecure=true
      - --api.dashboard=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      - --certificatesresolvers.leresolver.acme.httpchallenge=true
      ## Set your email address here, is for the generation of SSL certificates with Let's Encrypt.
      - --certificatesresolvers.leresolver.acme.email=aris@ripandis.com
      - --certificatesresolvers.leresolver.acme.storage=./acme.json
      - --certificatesresolvers.leresolver.acme.httpchallenge.entrypoint=web
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./acme.json:/acme.json"
    labels:
      # Traefik dashboard
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`dash.stats.web.id`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.tls.certresolver=leresolver"
      # Securing Traefik dashboard
      # - "traefik.http.routers.traefik.middlewares=authtraefik"
      # - "traefik.http.middlewares.authtraefik.basicauth.users=user:$$apr1$$q8eZFHjF$$Fvmkk//V6Btlaf2i/ju5n/"
      # global redirect to https
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

  umami:
    image: ghcr.io/mikecao/umami:postgresql-latest
    restart: always
    depends_on:
      - umami_db
    environment:
      DATABASE_URL: postgresql://postgres:secret@umami_db:5432/postgres
      DATABASE_TYPE: postgresql
      HASH_SALT: ${HASH_SALT:-f77d04be5960d4ffd3d1cd918ca6e23e}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.umami.rule=Host(`stats.web.id`)"
      - "traefik.http.routers.umami.entrypoints=websecure"
      - "traefik.http.services.umami.loadbalancer.server.port=3000"
      - "traefik.http.routers.umami.service=umami"
      - "traefik.http.routers.umami.tls.certresolver=leresolver"

  umami_db:
    image: postgres:12-alpine
    restart: always
    volumes:
      - ./sql/pgsql_schema.sql:/docker-entrypoint-initdb.d/schema.postgresql.sql:ro
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=secret

volumes:
  db_data:
    driver: local
