# mkdir -p jenkins_data ; sudo chown -R $(whoami): $_
# dc run --rm jenkins cat /var/jenkins_home/secrets/initialAdminPassword

version: '3.7'

services:
  pgsql:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secured}
      POSTGRES_USER: ${POSTGRES_USER:-jenkins}
      POSTGRES_DB: ${POSTGRES_DB:-jenkins}
    networks:
      - jenkinsnet
    restart: unless-stopped
    volumes:
      - db_data:/var/lib/postgresql/data

  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    depends_on:
      - pgsql
    volumes:
      - ./jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkinsnet

  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - '${MAILHOG_PORT:-1025}:1025'
      - '${MAILHOG_DASHBOARD_PORT:-8025}:8025'
    networks:
      - jenkinsnet

networks:
  jenkinsnet:
    driver: bridge

volumes:
  db_data:
