version: '3.6'

services:
  pdns-recursor:
    image: pschiffe/pdns-recursor:4.5-alpine
    restart: always
    ports:
      - '53:53'
      - '53:53/udp'
      - '8053:8082'
    environment:
      - PDNS_api_key=secret
      - PDNS_webserver=yes
      # - PDNS_webserver-allow-from=127.0.0.1,10.0.0.0/8,172.0.0.0/8,192.0.0.0/24
      - PDNS_webserver-allow-from=0.0.0.0/0
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_password=secret
