# https://computingforgeeks.com/running-powerdns-and-powerdns-admin-in-docker-containers/

version: '3.6'

services:
  powerdns:
    image: pschiffe/pdns-mysql:4.6
    hostname: ns1.example.com
    domainname: example.com
    depends_on:
      - mariadb
    links:
      - 'mariadb:mariadb'
    ports:
      - '5553:53'
      - '5553:53/udp'
      - '8081:8081'
    restart: always
    environment:
      - PDNS_gmysql_host=mariadb
      - PDNS_gmysql_port=3306
      - PDNS_gmysql_user=powerdns
      - PDNS_gmysql_dbname=powerdns
      - PDNS_gmysql_password=securedb
      - PDNS_master=yes
      - PDNS_api=yes
      - PDNS_api_key=secret
      - PDNS_webserver=yes
      - PDNS_webserver-allow-from=127.0.0.1,10.0.0.0/8,172.0.0.0/8,192.0.0.0/24
      - PDNS_webserver_address=0.0.0.0
      - PDNS_webserver_password=secret
      - PDNS_version_string=anonymous
      - PDNS_default_ttl=3600
      - PDNS_allow_notify_from=0.0.0.0
      - PDNS_allow_axfr_ips=127.0.0.1

  # pdns-recursor:
  #   image:  pschiffe/pdns-recursor:4.6
  #   ports:
  #     - '53:53'
  #     - '53:53/udp'
  #   restart: always
  #   environment:
  #     - PDNS_api_key=secret
  #     - PDNS_webserver=yes
  #     - PDNS_webserver-allow-from=127.0.0.1,10.0.0.0/8,172.0.0.0/8,192.0.0.0/24
  #     - PDNS_webserver_address=0.0.0.0
  #     - PDNS_webserver_password=secret

  mariadb:
    # image: yobasystems/alpine-mariadb:10.6
    image: jbergstroem/mariadb-alpine:10.6.8
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=powerdns
      - MYSQL_USER=powerdns
      - MYSQL_PASSWORD=securedb
      - MYSQL_ROOT_PASSWORD=securedb
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_general_ci

  pdns-admin:
    image: ngoduykhanh/powerdns-admin:latest
    restart: always
    ports:
      - '8053:80'
    depends_on:
      - mariadb
      - powerdns
    links:
      - mariadb
      - powerdns
    volumes:
      - pdns_admin_data:/data
    logging:
      driver: json-file
      options:
        max-size: 50m
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql://powerdns:securedb@mariadb/pdns_admin
      - GUNICORN_TIMEOUT=60
      - GUNICORN_WORKERS=2
      - GUNICORN_LOGLEVEL=DEBUG
      - OFFLINE_MODE=False
      - SECRET_KEY=secret
      - PDNS_API_URL=http://powerdns:8081/
      - PDNS_API_KEY=secret
      - PDNS_VERSION=4.6.2

  adminer:
    image: adminer:4-standalone
    restart: always
    ports:
      - '8006:8080'
    depends_on:
      - mariadb
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb
      - ADMINER_DESIGN=nette

volumes:
  mysql_data:
    driver: local
  pdns_admin_data:
    driver: local
