version: "3"
services:
  krakend_ce:
    image: devopsfaith/krakend:2.0
    volumes:
      - ./krakend:/etc/krakend
    ports:
      - "1234:1234"
      - "8080:8080"
      - "8090:8090"
    command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]
    depends_on:
      - fake_api
      - jaeger

  jwt_revoke:
    build:
      context: ./jwt-revoker
    ports:
      - "9000:8080"
    depends_on:
      - krakend_ce

  fake_api:
    image: jaxgeller/lwan
    volumes:
      - ./data:/lwan/wwwroot
    ports:
      - "8000:8080"
  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"

  kraken_designer:
    image: devopsfaith/krakendesigner:v2.0
    ports:
      - 8787:80

  grafana:
    build:
      dockerfile: Dockerfile
      context: ./grafana
    ports:
      - "3003:3000"

  influxdb:
    image: influxdb:1.8
    environment:
      - "INFLUXDB_DB=krakend"
      - "INFLUXDB_USER=krakend-dev"
      - "INFLUXDB_USER_PASSWORD=pas5w0rd"
      - "INFLUXDB_ADMIN_USER=admin"
      - "INFLUXDB_ADMIN_PASSWORD=supersecretpassword"
    ports:
      - "8086:8086"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"

  web:
    build:
      context: ./web
    ports:
      - "3000:3000"
